---
## katana configuration directory
config_dir: /opt/katana

## package list for installation
packages:
- vim
- bash-completion
- curl
- ca-certificates
- net-tools
- dnsutils
- tcpdump
- ethtool

## sshd configuration
sshd_config:
  Port: "{{ ansible_port }}"
  ListenAddress: "{{ ansible_host }}"
  PermitRootLogin: without-password
  PasswordAuthentication: "no"
  AllowUsers: root
  AllowGroups: root

## limits configuration
limit_nofile_hard: 1000000
limit_nofile_soft: 1000000
limit_nproc_hard: 10000
limit_nproc_soft: 10000
