---
## supported: nftables, none
firewall: none

## firewall configuration
firewall_config:
  network_adapter_access:
    - lo
  tcp_port_access:
    - 8084
    - 8082
  udp_port_access:
    - 8084
    - 8082
  #trusted_range:
  #  - 1.1.1.1/24
